# Generated by Django 4.1.7 on 2023-02-24 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servise',
            name='s_end',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Express.district'),
        ),
        migrations.AlterField(
            model_name='servise',
            name='s_start',
            field=models.CharField(default='', max_length=50),
        ),
    ]
