# Generated by Django 4.1.7 on 2023-02-24 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0002_servise_s_end_alter_servise_s_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servise',
            name='s_start',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Express.branch'),
        ),
    ]
