# Generated by Django 4.1.7 on 2023-02-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0003_alter_servise_s_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
