# Generated by Django 4.1.7 on 2023-02-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0004_alter_branch_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servise',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
