# Generated by Django 4.1.7 on 2023-02-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0005_servise_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servise',
            old_name='odate',
            new_name='sdate',
        ),
        migrations.AddField(
            model_name='servise',
            name='status',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='servise',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Express.categories'),
        ),
    ]
