# Generated by Django 4.1.7 on 2023-02-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0006_rename_odate_servise_sdate_servise_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servise',
            name='price',
        ),
    ]
