# Generated by Django 4.1.7 on 2023-02-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Express', '0007_remove_servise_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoriess',
            name='picture',
        ),
    ]
